// 本文件由 scripts/gen_dart_labels.py 从 configs/classes.json 生成，请勿手工编辑。
// 手工改动会在下次生成时被覆盖；要改类别请改 configs/classes.json。

/// 一个检测类别。`id` 必须与 YOLO 标签索引一致。
class Label {
  const Label({
    required this.id,
    required this.nameEn,
    required this.nameZh,
    required this.group,
    required this.priority,
    required this.announced,
  });

  final int id;
  final String nameEn;
  final String nameZh;
  final String group;

  /// P0 表示可能危险，播报可插队；P1 排队播。
  final String priority;

  /// false 表示这类东西不该播报（如 streetlight：到处都有、又不可行动）。
  final bool announced;

  @override
  String toString() => 'Label($id, $nameEn, $nameZh)';
}

/// 全部类别，按 id 升序。
const List<Label> kLabels = <Label>[
  Label(
    id: 0,
    nameEn: 'footbridge_entrance',
    nameZh: '天橋入口',
    group: 'footbridge',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 1,
    nameEn: 'stairs',
    nameZh: '樓梯',
    group: 'footbridge',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 2,
    nameEn: 'escalator_outdoor',
    nameZh: '戶外扶梯',
    group: 'footbridge',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 3,
    nameEn: 'elevator',
    nameZh: '升降機',
    group: 'footbridge',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 4,
    nameEn: 'ramp',
    nameZh: '斜道',
    group: 'footbridge',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 5,
    nameEn: 'footbridge_railing',
    nameZh: '天橋欄杆',
    group: 'footbridge',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 6,
    nameEn: 'pedestrian',
    nameZh: '行人',
    group: 'obstacle',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 7,
    nameEn: 'bin',
    nameZh: '垃圾桶',
    group: 'obstacle',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 8,
    nameEn: 'bollard',
    nameZh: '護柱',
    group: 'obstacle',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 9,
    nameEn: 'traffic_cone',
    nameZh: '交通錐',
    group: 'obstacle',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 10,
    nameEn: 'barrier_water',
    nameZh: '水馬',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 11,
    nameEn: 'bicycle',
    nameZh: '單車',
    group: 'obstacle',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 12,
    nameEn: 'scooter',
    nameZh: '滑板車',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 13,
    nameEn: 'push_cart',
    nameZh: '手推車',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 14,
    nameEn: 'step',
    nameZh: '台階',
    group: 'obstacle',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 15,
    nameEn: 'tactile_paving',
    nameZh: '盲道',
    group: 'guide',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 16,
    nameEn: 'zebra_crossing',
    nameZh: '斑馬線',
    group: 'guide',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 17,
    nameEn: 'glass_door',
    nameZh: '玻璃門',
    group: 'indoor',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 18,
    nameEn: 'door',
    nameZh: '推拉門',
    group: 'indoor',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 19,
    nameEn: 'escalator_indoor',
    nameZh: '商場扶梯',
    group: 'indoor',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 20,
    nameEn: 'sign_pictogram',
    nameZh: '指示牌',
    group: 'indoor',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 21,
    nameEn: 'glass_door_indoor',
    nameZh: '商場玻璃門',
    group: 'indoor',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 22,
    nameEn: 'shop_front',
    nameZh: '店鋪門面',
    group: 'classifier',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 23,
    nameEn: 'fork_in_road',
    nameZh: '分岔路口',
    group: 'guide',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 24,
    nameEn: 'caution_slippery',
    nameZh: '小心地滑',
    group: 'obstacle',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 25,
    nameEn: 'crowds_of_people_queuing',
    nameZh: '排隊人潮',
    group: 'obstacle',
    priority: 'P0',
    announced: true,
  ),
  Label(
    id: 26,
    nameEn: 'fence',
    nameZh: '圍欄',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 27,
    nameEn: 'barrier_fencing',
    nameZh: '工程圍網',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 28,
    nameEn: 'scaffold',
    nameZh: '鷹架',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 29,
    nameEn: 'road_excavation',
    nameZh: '掘路工程',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 30,
    nameEn: 'power_distribution_box',
    nameZh: '配電箱',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 31,
    nameEn: 'goods',
    nameZh: '街邊貨物',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 32,
    nameEn: 'goods_rack',
    nameZh: '貨物架',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 33,
    nameEn: 'cardboard',
    nameZh: '紙皮',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 34,
    nameEn: 'table',
    nameZh: '桌椅',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 35,
    nameEn: 'roll_up_banner_stand',
    nameZh: '易拉架',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 36,
    nameEn: 'billboard',
    nameZh: '廣告看板',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 37,
    nameEn: 'traffic_cone_connector_rod',
    nameZh: '交通錐連接杆',
    group: 'obstacle',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 38,
    nameEn: 'abrasion_resistant_steel_plates',
    nameZh: '鋪路鋼板',
    group: 'obstacle',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 39,
    nameEn: 'hand_truck',
    nameZh: '搬運手推車',
    group: 'obstacle',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 40,
    nameEn: 'pallet',
    nameZh: '唧車',
    group: 'obstacle',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 41,
    nameEn: 'pushchair',
    nameZh: '嬰兒車',
    group: 'obstacle',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 42,
    nameEn: 'broken_tree',
    nameZh: '樹木',
    group: 'obstacle',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 43,
    nameEn: 'tree_root_on_the_road',
    nameZh: '地面樹根',
    group: 'obstacle',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 44,
    nameEn: 'cycle_path',
    nameZh: '單車徑',
    group: 'guide',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 45,
    nameEn: 'streetlight',
    nameZh: '路燈',
    group: 'obstacle',
    priority: 'P2',
    announced: false,
  ),
  Label(
    id: 46,
    nameEn: 'sign_post',
    nameZh: '標誌桿',
    group: 'obstacle',
    priority: 'P2',
    announced: false,
  ),
  Label(
    id: 47,
    nameEn: 'bucket',
    nameZh: '水桶',
    group: 'obstacle',
    priority: 'P2',
    announced: true,
  ),
  Label(
    id: 48,
    nameEn: 'obstacle',
    nameZh: '障礙物',
    group: 'obstacle',
    priority: 'P1',
    announced: true,
  ),
  Label(
    id: 49,
    nameEn: 'escalator',
    nameZh: '扶梯',
    group: 'footbridge',
    priority: 'P1',
    announced: true,
  ),
];

/// 模型输出维度。推理结果长度与之不符即为模型与类别表不匹配。
const int kNumClasses = 50;

/// 播报优先级顺序（先 announced，再 P0 → P1，再 id）。
const List<int> kAnnouncementOrder = <int>[
  0, 1, 2, 3, 4, 6, 7, 8, 9, 11, 14, 17, 19, 21, 23, 24, 25, 5, 10, 12, 13, 15, 16, 18, 20, 22, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 48, 49, 37, 38, 39, 40, 41, 42, 43, 44, 47, 45, 46,
];

/// 按 id 取类别。id 越界时返回 null —— 不要静默回退到 0，那会掩盖模型/类别表不匹配。
Label? labelOf(int id) => (id >= 0 && id < kLabels.length) ? kLabels[id] : null;
